GET http://localhost:5260/users

###

GET http://localhost:5260/users/2

###
POST  http://localhost:5260/users
Content-Type: application/json

{
    "userName": "sagTole",
    "password": "sag333",
    "email": "milad@test.coms"
}

###
PUT  http://localhost:5260/users/35c68613-3cae-4d10-838b-d06c7d050b1b
Content-Type: application/json

{
    "userName": "Usersag",
    "password": "Pass123",
    "email": "milad@test.com"
}

###
DELETE   http://localhost:5260/users/c0e2aedb-e19d-4cac-87b3-0f8dec1afece


### FRIEND REQUEST =======================
POST  http://localhost:5260/FriendRequests
Content-Type: application/json

{
    "requesterId": "3",
    "addresseeId": "2"
}

###
PUT  http://localhost:5260/FriendRequests/4baa703e-c8a7-46d1-8605-51d67935d068
Content-Type: application/json

{
    "requesterId": "3",
    "addresseeId": "2",
    "status": 1
}

###
GET http://localhost:5260/FriendRequests/3/sent
###
GET http://localhost:5260/FriendRequests/2/received